- name: backup mysql
  hosts: all
  vars:
    mysql_backup_dir: /db/backup
    backup_user: root
    storage_resource_uri: ""
    azcopy_bin_path: "{{ mysql_backup_dir }}"
    blob_sas_token: ""
  
  tasks:
    # tasks file for mysql-backup
    - name: create backup directory
      become: true
      file:
        path: "{{ mysql_backup_dir }}"
        state: directory
        owner: "{{ backup_user }}"
        group: "{{ backup_user }}"
        mode: 0700

    - name: create backup script
      become: true
      template:
        src: etc-crond-mysql-backup.j2
        dest: "{{ mysql_backup_dir }}/mysql-backup.sh"
        mode: 0755
        owner: "{{ backup_user }}"
        group: "{{ backup_user }}"

    - name: Configure backup cron job.
      cron:
        name: "Backup cron job"
        minute: "*/2"
        hour: "*"
        day: "*"
        month: "*"
        weekday: "*"
        user: "{{ backup_user }}"
        job: "{{ mysql_backup_dir }}/mysql-backup.sh"
        state: "present"

    - name: Pass variables to role
      ansible.builtin.include_role:
        name: eduardolmedeiros.azcopy
      vars:
        azcopy_username: "{{ backup_user }}"
        azcopy_group: "{{ backup_user }}"
